# Generated by Django 4.1.7 on 2023-03-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogado_online', models.BooleanField()),
                ('ano_criacao', models.IntegerField()),
            ],
        ),
    ]
